### ISSUE TITLE
На версии прошивки 2.5 ошибки "This plugin generated a warning from the characteristic 'Heating Threshold Temperature': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://git.io/JtMGR for more info."

### ISSUE THREAD

**Issue by tamvodopad** [wiistriker/homebridge-terneo-heatfloor#4]
Имею два датчика идентично настроенные.

При подключении  только одного все работает ок. При конфиге для двух ошибки

`[Теплый пол в корридоре] cmd:1 response 
[24/10/2021, 08:14:04] [Теплый пол в корридоре] [Terneo] [WARNING] State update error Error: Response has no parameters data
    at /usr/lib/node_modules/homebridge-terneo-heatfloor/index.js:209:31
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
[homebridge-terneo-heatfloor] This plugin generated a warning from the characteristic 'Heating Threshold Temperature': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://git.io/JtMGR for more info.`

Версия прошиивки 2.5

**Comment by wiistriker** [comment]
Хорошо, попробую повторить поведение

**Comment by wiistriker** [comment]
fixed in https://github.com/wiistriker/homebridge-terneo-heatfloor/pull/6

**Comment by tamvodopad** [comment]
Спасибо. Все работает хорошо!
